language: node_js
node_js: 8

before_script:
    - npm install firebase-tools -g
    - cd functions && npm install

script:
    - firebase deploy --token "1/7FPH6RDCtEKbCEJYfPZqnSeaqipJKjg0868SqQ1lLpULVyhvODRtFD6LOC2RdS_u"